twitter_to_impurl:
    ysimp1 : https://agent.electricimp.com/SOxdG87iB9SP
    ysimp2 : https://agent.electricimp.com/osL1eTvExzIS
    ysimp3 : https://agent.electricimp.com/E68XchIaOzDo
watch_every: 5
bmp_min: 39
bmp_max: 219
